POST http://localhost:5149/api/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "testPwd"
}

###

POST http://localhost:5149/api/auth/register
Content-Type: application/json

{
    "email": "test@test.com",
    "username": "test",
    "password": "testPwd"
}

###

