POST http://localhost:5149/api/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "testPwd"
}

###

POST http://localhost:5149/api/auth/register
Content-Type: application/json

{
    "email": "test@test.com",
    "username": "test",
    "password": "testPwd"
}

###

POST http://localhost:5149/api/leaderboard/submit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0ZXN0QHRlc3QuY29tIiwiZXhwIjoxNzc3MTI3NTA0fQ.kOrNm3LIOIfzHlAm-mrtqJLt5BQPXRTfJIfXv-xFWSs

{
    "amount": 30,
    "createdAt": "2026-04-24T14:18:23.573Z"
}

###

GET http://localhost:5149/api/leaderboard/score/2